/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.hasanozgan.komandante.todoapp

import io.ktor.application.Application
import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test fun testAppHasAGreeting() {
//        val classUnderTest = Application()
//        assertNotNull(classUnderTest., "app should have a greeting")
    }
}
